<a href="https://colab.research.google.com/github/kaliappan01/PCA/blob/main/Non_linear_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [ ]:
iris_data = datasets.load_iris()
X = iris_data.data
y = iris_data.target
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state= 42)

In [ ]:
my_tree = DecisionTreeClassifier(max_leaf_nodes=3, random_state=0)
my_tree.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=3,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
from sklearn.tree import _tree

def find_rules(tree, features):
  dec_tree = tree.tree_
  def visitor(node, depth):
    indent = " "*depth
    if dec_tree.feature[node] != _tree.TREE_UNDEFINED:
      print("{}if <{}> <={}:".format(indent, features[node], round(dec_tree.threshold[node], 2)))
      visitor(dec_tree.children_left[node], depth+1)
      print("{}else: ".format(indent))
      visitor(dec_tree.children_right[node], depth+1)
    else:
       print("{}return {}".format(indent, dec_tree.value[node]))
  visitor(0,1)

In [ ]:
find_rules(my_tree, iris_data.feature_names)

 if <sepal length (cm)> <=0.8:
  return [[35.  0.  0.]]
 else: 
  if <petal length (cm)> <=4.75:
   return [[ 0. 34.  1.]]
  else: 
   return [[ 0.  5. 37.]]


In [ ]:
boston_data = datasets.load_boston()
print(boston_data.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [ ]:
from sklearn import svm,linear_model
from sklearn.metrics import mean_absolute_error,classification_report
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [ ]:
lin_svm_model = svm.LinearSVR(random_state= 42)
lin_svm_model.fit(X_train,y_train)
# lin_svm_pred = lin_svm_model.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_intercept=True,
          intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
          random_state=42, tol=0.0001, verbose=0)

In [ ]:
print(lin_svm_model.score(X_test,y_test))

0.948832161622023


In [ ]:
svr_model = svm.SVR()
svr_model.fit(X_train,y_train)
# lin_svm_pred = lin_svm_model.predict(X_test)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
print(svr_model.score(X_test,y_test))

0.9533513702061646


In [ ]:
lin_reg = linear_model.LinearRegression()
lin_reg.fit(X_train,y_train)
# lin_reg_pred = lin_reg.predict(X_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
print(lin_reg.score(X_test,y_test))

0.9487283360348984


<font size =  10 > POLYNOMIAL FEATURES <FONT>

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
X = np.arange(6).reshape(2,3)

In [ ]:
poly = PolynomialFeatures(degree = 2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  2.,  0.,  0.,  0.,  1.,  2.,  4.],
       [ 1.,  3.,  4.,  5.,  9., 12., 15., 16., 20., 25.]])

In [ ]:
x = np.arange(5)
y = x**3 + x**2- x +x
np.stack([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 0,  2, 12, 36, 80]])

In [ ]:
model = Pipeline([('poly',PolynomialFeatures(degree=3)),
                   ('Linear' ,LinearRegression())])

In [ ]:
model.fit(x[:,None],y)

Pipeline(memory=None,
         steps=[('poly',
                 PolynomialFeatures(degree=3, include_bias=True,
                                    interaction_only=False, order='C')),
                ('Linear',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [ ]:
model.named_steps['Linear'].coef_

array([0.00000000e+00, 3.33066907e-14, 1.00000000e+00, 1.00000000e+00])

<font size = 10 > REGULARIZATION </FONT>

In [ ]:
X_b = boston_data.data
y_b = boston_data.target
X_b_train,X_b_test,y_b_train,y_b_test = train_test_split(X_b,y_b,random_state= 42)

In [ ]:
LIN_REG  = linear_model.LinearRegression()
LIN_REG.fit(X_b_train,y_b_train)
for coef,label in zip(LIN_REG.coef_,boston_data.feature_names):
  print("{:10.4f}".format(coef),label)

   -0.1283 CRIM
    0.0296 ZN
    0.0489 INDUS
    2.7735 CHAS
  -16.2388 NOX
    4.3688 RM
   -0.0092 AGE
   -1.4009 DIS
    0.2578 RAD
   -0.0100 TAX
   -0.9231 PTRATIO
    0.0132 B
   -0.5176 LSTAT


the linear regression model leads overfitting 

In [ ]:
Ridge_model = linear_model.Ridge(alpha = 1)
Ridge_model.fit(X_b_train,y_b_train)
for coef,label in zip(Ridge_model.coef_,boston_data.feature_names):
  print("{:10.4f}".format(coef),label)

   -0.1238 CRIM
    0.0314 ZN
    0.0177 INDUS
    2.5428 CHAS
   -8.7725 NOX
    4.3798 RM
   -0.0154 AGE
   -1.2909 DIS
    0.2441 RAD
   -0.0108 TAX
   -0.8335 PTRATIO
    0.0135 B
   -0.5344 LSTAT


the Ridge regression uses L2 norm for reducing the complexity of the model

In [ ]:
Lasso_model = linear_model.Lasso(alpha = 1)
Lasso_model.fit(X_b_train,y_b_train)
for coef,label in zip(Lasso_model.coef_,boston_data.feature_names):
  print("{:10.4f}".format(coef),label)

   -0.0839 CRIM
    0.0265 ZN
   -0.0000 INDUS
    0.0000 CHAS
   -0.0000 NOX
    1.5454 RM
    0.0135 AGE
   -0.5828 DIS
    0.2074 RAD
   -0.0112 TAX
   -0.7050 PTRATIO
    0.0120 B
   -0.7578 LSTAT


Lasso model uses L1 norm for reducing the overfitting  
and as you see some features are neglected completely